name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        uses: huggingface/hub-sync@v1
        with:
          # Your GitHub repo path
          github_repo_id: Akash671/cnn-image-classifier
          # Your Hugging Face Space path
          huggingface_repo_id: Akash671/cnn-image-classifier
          # Ensure this secret is set in GitHub Settings
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
